import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import MarkdownIt from 'markdown-it';
import { parse as parseYaml } from 'yaml';

const GENERATED = '<!-- Generated by npm run build';
const DATE_FOLDER = /^\d{8}$/;
const markdown = new MarkdownIt({ html: false });
const escape = (value) => markdown.utils.escapeHtml(String(value));

// Posts stay next to their Markdown sources, so relative image paths still work.
markdown.renderer.rules.link_open = (tokens, index, options, env, renderer) => {
  const token = tokens[index];
  const href = token.attrGet('href');
  if (href && !/^(?:[a-z][a-z\d+.-]*:|\/\/)/i.test(href)) {
    token.attrSet('href', href.replace(/\.md(?=[?#]|$)/i, '.html'));
  }
  return renderer.renderToken(tokens, index, options);
};
markdown.renderer.rules.table_open = () => '<div class="table-scroll" role="region" aria-label="Table" tabindex="0"><table>\n';
markdown.renderer.rules.table_close = () => '</table></div>\n';

function plainText(inline) {
  return (inline?.children ?? []).map((token) => {
    if (['text', 'code_inline', 'image'].includes(token.type)) return token.content;
    if (['softbreak', 'hardbreak'].includes(token.type)) return ' ';
    return '';
  }).join('').trim();
}

function shortText(text, limit = 180) {
  const normalized = text.replace(/\s+/g, ' ').trim();
  if (normalized.length <= limit) return normalized;
  return normalized.slice(0, limit).replace(/\s+\S*$/, '').trimEnd() + '…';
}

export function folderDate(folder) {
  if (!DATE_FOLDER.test(folder)) throw new Error(`Expected a YYYYMMDD date folder: ${folder}`);
  const iso = `${folder.slice(0, 4)}-${folder.slice(4, 6)}-${folder.slice(6, 8)}`;
  const date = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== iso) {
    throw new Error(`Invalid date folder: ${folder}`);
  }
  return iso;
}

function displayDate(iso) {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC',
  }).format(new Date(`${iso}T00:00:00Z`));
}

export function parsePost(source, folder, filename) {
  let body = source.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
  let metadata = {};
  if (body.startsWith('---\n')) {
    const match = body.match(/^---\n([\s\S]*?)\n---(?:\n|$)/);
    if (!match) throw new Error('YAML front matter needs a closing --- line.');
    metadata = parseYaml(match[1]) ?? {};
    body = body.slice(match[0].length);
    if (typeof metadata !== 'object' || Array.isArray(metadata)) {
      throw new Error('YAML front matter must contain named fields.');
    }
  }
  for (const field of ['title', 'description', 'author']) {
    if (metadata[field] !== undefined && (typeof metadata[field] !== 'string' || !metadata[field].trim())) {
      throw new Error(`${field} must be a nonempty string.`);
    }
  }
  let tags = metadata.tags ?? ['uncategorized'];
  if (typeof tags === 'string') tags = [tags];
  if (!Array.isArray(tags) || tags.some((tag) => typeof tag !== 'string' || !tag.trim())) {
    throw new Error('tags must be a string or a list of nonempty strings.');
  }
  tags = [...new Set(tags.map((tag) => tag.trim().toLowerCase()))].sort();
  if (!tags.length) tags = ['uncategorized'];

  const tokens = markdown.parse(body, {});
  const leadingTitle = tokens[0]?.type === 'heading_open' && tokens[0].tag === 'h1';
  const fallbackTitle = path.basename(filename, path.extname(filename)).replace(/[-_]+/g, ' ');
  const title = metadata.title?.trim() || (leadingTitle ? plainText(tokens[1]) : fallbackTitle);
  if (leadingTitle) tokens.splice(0, 3);

  // Stable heading anchors support Markdown links within and between posts.
  const headingIds = new Set();
  for (let index = 0; index < tokens.length; index++) {
    if (tokens[index].type !== 'heading_open') continue;
    const base = plainText(tokens[index + 1]).toLowerCase().normalize('NFKD')
      .replace(/[^\p{L}\p{N}\s-]/gu, '').trim().replace(/\s+/g, '-') || 'section';
    let id = base;
    let suffix = 2;
    while (headingIds.has(id)) id = `${base}-${suffix++}`;
    headingIds.add(id);
    tokens[index].attrSet('id', id);
  }

  const paragraph = tokens.findIndex((token) => token.type === 'paragraph_open');
  const description = metadata.description?.trim() || shortText(plainText(tokens[paragraph + 1]));
  const text = tokens.filter((token) => token.type === 'inline').map(plainText).join(' ');
  const date = folderDate(folder);
  const htmlFilename = filename.replace(/\.md$/i, '.html');
  return {
    title, description, date, displayDate: displayDate(date), tags,
    author: metadata.author?.trim() || '',
    readingMinutes: Math.max(1, Math.ceil(text.split(/\s+/).filter(Boolean).length / 200)),
    folder, filename, htmlFilename,
    href: `${encodeURIComponent(folder)}/${encodeURIComponent(htmlFilename)}`,
    html: markdown.renderer.render(tokens, markdown.options, {}),
  };
}

export async function loadPosts(blogDir) {
  const posts = [];
  for (const directory of await readdir(blogDir, { withFileTypes: true })) {
    if (!directory.isDirectory() || !DATE_FOLDER.test(directory.name)) continue;
    folderDate(directory.name);
    for (const file of await readdir(path.join(blogDir, directory.name), { withFileTypes: true })) {
      if (!file.isFile() || !/\.md$/i.test(file.name)) continue;
      try {
        const source = await readFile(path.join(blogDir, directory.name, file.name), 'utf8');
        posts.push(parsePost(source, directory.name, file.name));
      } catch (error) {
        throw new Error(`${directory.name}/${file.name}: ${error.message}`, { cause: error });
      }
    }
  }
  return posts.sort((a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title, 'en') || a.filename.localeCompare(b.filename, 'en'));
}

function tagLinks(tags, base = '') {
  return tags.map((tag) => `<a class="post-tag" href="${base}?tag=${encodeURIComponent(tag)}" data-filter-tag="${escape(tag)}">${escape(tag)}</a>`).join('');
}

function postCard(post) {
  return `<article class="post-card" data-tags="${escape(JSON.stringify(post.tags))}">
    <div class="post-meta"><time datetime="${post.date}">${post.displayDate}</time><span aria-hidden="true">·</span><span>${post.readingMinutes} min read</span></div>
    <h3><a class="post-title-link" href="${post.href}">${escape(post.title)}</a></h3>
    <p class="post-excerpt">${escape(post.description)}</p>
    <div class="post-tags" aria-label="Post tags">${tagLinks(post.tags)}</div>
    <span class="post-read-link" aria-hidden="true">Read post <span>→</span></span>
  </article>`;
}

function indexContent(posts) {
  const counts = new Map();
  for (const post of posts) for (const tag of post.tags) counts.set(tag, (counts.get(tag) ?? 0) + 1);
  const tags = [...counts].sort(([a, ac], [b, bc]) => bc - ac || a.localeCompare(b, 'en'));
  return `<header class="page-heading blog-heading">
    <h1>Blog</h1>
    <p>Project updates, engineering notes, and ideas from Tau.rs.</p>
  </header>
  <div class="blog-layout">
    <section class="blog-posts" aria-labelledby="posts-heading">
      <div class="posts-toolbar">
        <h2 id="posts-heading">Latest posts</h2>
        <p id="post-count" role="status" aria-live="polite">${posts.length} ${posts.length === 1 ? 'post' : 'posts'}</p>
      </div>
      <div class="post-grid">${posts.map(postCard).join('\n')}</div>
      <div class="blog-empty" id="blog-empty" ${posts.length ? 'hidden' : ''}>
        <h3>${posts.length ? 'No posts match this tag.' : 'No posts published yet.'}</h3>
        <p>${posts.length ? 'Choose another tag or return to all posts.' : 'Check back soon for news from Tau.rs.'}</p>
        <button class="button button-secondary" type="button" data-filter-tag="" ${posts.length ? '' : 'hidden'}>Show all posts</button>
      </div>
    </section>
    <aside class="blog-sidebar" aria-label="Blog navigation">
      <section class="tag-filters" id="tag-filters" aria-labelledby="tags-heading" hidden>
        <h2 id="tags-heading">Filter by tag</h2>
        <div class="tag-filter-list">
          <button class="tag-filter" type="button" data-filter-tag="" aria-pressed="true"><span>All posts</span><span class="tag-count">${posts.length}</span></button>
          ${tags.map(([tag, count]) => `<button class="tag-filter" type="button" data-filter-tag="${escape(tag)}" aria-pressed="false"><span><span class="tag-hash" aria-hidden="true">#</span>${escape(tag)}</span><span class="tag-count">${count}</span></button>`).join('\n')}
        </div>
      </section>
      <noscript><p class="filter-note">All posts are shown. Enable JavaScript to filter by tag.</p></noscript>
      <section class="recent-posts" aria-labelledby="recent-heading">
        <h2 id="recent-heading">Recent posts</h2>
        <ul>${posts.slice(0, 5).map((post) => `<li><a href="${post.href}">${escape(post.title)}</a><time datetime="${post.date}">${post.displayDate}</time></li>`).join('\n')}</ul>
      </section>
    </aside>
  </div>`;
}

function articleContent(post) {
  return `<a class="back-link" href="../"><span aria-hidden="true">←</span> All posts</a>
  <article class="post-article">
    <header class="post-header">
      <div class="post-tags" aria-label="Post tags">${tagLinks(post.tags, '../')}</div>
      <h1>${escape(post.title)}</h1>
      <div class="post-meta"><time datetime="${post.date}">${post.displayDate}</time><span aria-hidden="true">·</span><span>${post.readingMinutes} min read</span>${post.author ? `<span aria-hidden="true">·</span><span>${escape(post.author)}</span>` : ''}</div>
    </header>
    <div class="post-content">${post.html}</div>
    <footer class="post-end"><a class="back-link" href="../"><span aria-hidden="true">←</span> Back to the blog</a></footer>
  </article>`;
}

function renderPage(template, values) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!(key in values)) throw new Error(`Unknown template placeholder: ${key}`);
    return values[key];
  });
}

export async function buildBlog(root) {
  const blogDir = path.join(root, 'blog');
  const posts = await loadPosts(blogDir);
  const template = await readFile(path.join(root, 'templates/blog.html'), 'utf8');
  const pages = new Map([['index.html', renderPage(template, {
    title: 'Blog — Tau.rs',
    description: 'Project updates, engineering notes, and ideas from Tau.rs, a lightweight model inference engine written in Rust.',
    root: '../', blog: './', current: 'aria-current="page"', mainClass: 'blog-main',
    scripts: '<script src="../assets/blog.js" defer></script>', content: indexContent(posts),
  })]]);
  for (const post of posts) {
    pages.set(`${post.folder}/${post.htmlFilename}`, renderPage(template, {
      title: escape(`${post.title} — Tau.rs`), description: escape(post.description),
      root: '../../', blog: '../', current: '', mainClass: 'post-main', scripts: '',
      content: articleContent(post),
    }));
  }

  // Remove only previously generated articles whose Markdown source was removed.
  for (const directory of await readdir(blogDir, { withFileTypes: true })) {
    if (!directory.isDirectory() || !DATE_FOLDER.test(directory.name)) continue;
    for (const file of await readdir(path.join(blogDir, directory.name), { withFileTypes: true })) {
      const relative = `${directory.name}/${file.name}`;
      if (!file.isFile() || !file.name.endsWith('.html') || pages.has(relative)) continue;
      const target = path.join(blogDir, relative);
      if ((await readFile(target, 'utf8')).startsWith(`<!doctype html>\n${GENERATED}`)) await rm(target);
    }
  }
  for (const [relative, html] of pages) await writeFile(path.join(blogDir, relative), html);

  // Publish only static site files; dependencies and authoring tools stay out.
  const output = path.join(root, '_site');
  await rm(output, { recursive: true, force: true });
  await mkdir(output, { recursive: true });
  for (const item of ['index.html', 'assets', 'blog', '.nojekyll']) {
    await cp(path.join(root, item), path.join(output, item), { recursive: true });
  }
  return posts;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = fileURLToPath(new URL('../', import.meta.url));
  try {
    const posts = await buildBlog(root);
    console.log(`Built ${posts.length} blog posts and their index. GitHub Pages output: _site/`);
  } catch (error) {
    console.error(`Blog build failed: ${error.message}`);
    process.exitCode = 1;
  }
}
